### 1.

In [2]:
import numpy as np

def jacobi(A, b, x0, iterations):
    D = np.diag(A)
    R = A - np.diagflat(D)
    x = x0
    for i in range(iterations):
        x = (b - np.dot(R, x)) / D
        print(f'Iteración {i+1}: {x}')
    return x

#### a.

In [4]:
A1 = np.array([[3, -1, 1], [3, 6, 2], [3, 3, 7]])
b1 = np.array([1, 0, 4])

x0 = np.zeros(len(b1))

jacobi(A1, b1, x0, 2)

Iteración 1: [0.33333333 0.         0.57142857]
Iteración 2: [ 0.14285714 -0.35714286  0.42857143]


array([ 0.14285714, -0.35714286,  0.42857143])

#### b.

In [6]:
A2 = np.array([[10, -1, 0], [-1, 10, -2], [0, -2, 10]])
b2 = np.array([9, 7, 6])

x0 = np.zeros(len(b2))

jacobi(A2, b2, x0, 2)

Iteración 1: [0.9 0.7 0.6]
Iteración 2: [0.97 0.91 0.74]


array([0.97, 0.91, 0.74])

#### c.

In [8]:
A3 = np.array([[10, 5, 0], [5, 10, -4], [0, -4, 8]])
b3 = np.array([6, 25, -11])

x0 = np.zeros(len(b3))

jacobi(A3, b3, x0, 2)

Iteración 1: [ 0.6    2.5   -1.375]
Iteración 2: [-0.65   1.65  -0.125]


array([-0.65 ,  1.65 , -0.125])

#### d.

In [10]:
A4 = np.array([[4, 1, 1, 0, 1], [-1, -3, 1, 1, 0], [2, 1, 5, -1, -1], [-1, -1, -1, 4, 0], [0, 2, -1, 1, 4]])
b4 = np.array([6, 6, 6, 6, 6])

x0 = np.zeros(len(b4))

jacobi(A4, b4, x0, 2)

Iteración 1: [ 1.5 -2.   1.2  1.5  1.5]
Iteración 2: [ 1.325 -1.6    1.6    1.675  2.425]


array([ 1.325, -1.6  ,  1.6  ,  1.675,  2.425])

### 2.

In [12]:
def gauss_seidel(A, b, x0, iterations):
    n = len(b)
    x = x0.copy()
    for k in range(iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        x = x_new
        print(f'Iteración {k+1}: {x}')
    return x

#### a.

In [14]:
x0 = np.zeros(len(b1))
gauss_seidel(A1, b1, x0, 2)

Iteración 1: [ 0.33333333 -0.16666667  0.5       ]
Iteración 2: [ 0.11111111 -0.22222222  0.61904762]


array([ 0.11111111, -0.22222222,  0.61904762])

#### b.

In [16]:
x0 = np.zeros(len(b2))
gauss_seidel(A2, b2, x0, 2)

Iteración 1: [0.9   0.79  0.758]
Iteración 2: [0.979  0.9495 0.7899]


array([0.979 , 0.9495, 0.7899])

#### c.

In [18]:
x0 = np.zeros(len(b3))
gauss_seidel(A3, b3, x0, 2)

Iteración 1: [ 0.6    2.2   -0.275]
Iteración 2: [-0.5    2.64  -0.055]


array([-0.5  ,  2.64 , -0.055])

#### d.

In [20]:
x0 = np.zeros(len(b4))
gauss_seidel(A4, b4, x0, 2)

Iteración 1: [ 1.5     -2.5      1.1      1.525    2.64375]
Iteración 2: [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]


array([ 1.1890625 , -1.52135417,  1.86239583,  1.88252604,  2.25564453])

### 3.

In [22]:
def jacobi_tol(A, b, x0, tol):
    D = np.diag(A)
    R = A - np.diagflat(D)
    x = x0
    iteration = 0
    while True:
        x_new = (b - np.dot(R, x)) / D
        iteration += 1
        if np.linalg.norm(x_new - x, np.inf) < tol:
            break
        x = x_new
        print(f'Iteración {iteration}: {x}')
    return x

#### a.

In [24]:
x0 = np.zeros(len(b1))
jacobi_tol(A1, b1, x0, 1e-3)

Iteración 1: [0.33333333 0.         0.57142857]
Iteración 2: [ 0.14285714 -0.35714286  0.42857143]
Iteración 3: [ 0.07142857 -0.21428571  0.66326531]
Iteración 4: [ 0.04081633 -0.25680272  0.63265306]
Iteración 5: [ 0.03684807 -0.23129252  0.66399417]
Iteración 6: [ 0.03490444 -0.23975543  0.6547619 ]
Iteración 7: [ 0.03516089 -0.23570619  0.65922185]
Iteración 8: [ 0.03502399 -0.23732106  0.65737656]


array([ 0.03502399, -0.23732106,  0.65737656])

#### b.

In [26]:
x0 = np.zeros(len(b2))
jacobi_tol(A2, b2, x0, 1e-3)

Iteración 1: [0.9 0.7 0.6]
Iteración 2: [0.97 0.91 0.74]
Iteración 3: [0.991 0.945 0.782]
Iteración 4: [0.9945 0.9555 0.789 ]
Iteración 5: [0.99555 0.95725 0.7911 ]


array([0.99555, 0.95725, 0.7911 ])

#### c.

In [28]:
x0 = np.zeros(len(b3))
jacobi_tol(A3, b3, x0, 1e-3)

Iteración 1: [ 0.6    2.5   -1.375]
Iteración 2: [-0.65   1.65  -0.125]
Iteración 3: [-0.225  2.775 -0.55 ]
Iteración 4: [-0.7875  2.3925  0.0125]
Iteración 5: [-0.59625  2.89875 -0.17875]
Iteración 6: [-0.849375  2.726625  0.074375]
Iteración 7: [-0.7633125  2.9544375 -0.0116875]
Iteración 8: [-0.87721875  2.87698125  0.10221875]
Iteración 9: [-0.83849063  2.97949688  0.06349063]
Iteración 10: [-0.88974844  2.94464156  0.11474844]
Iteración 11: [-0.87232078  2.99077359  0.09732078]
Iteración 12: [-0.8953868  2.9750887  0.1203868]
Iteración 13: [-0.88754435  2.99584812  0.11254435]
Iteración 14: [-0.89792406  2.98878992  0.12292406]
Iteración 15: [-0.89439496  2.99813165  0.11939496]
Iteración 16: [-0.89906583  2.99495546  0.12406583]
Iteración 17: [-0.89747773  2.99915924  0.12247773]
Iteración 18: [-0.89957962  2.99772996  0.12457962]
Iteración 19: [-0.89886498  2.99962166  0.12386498]


array([-0.89886498,  2.99962166,  0.12386498])

#### d.

In [30]:
x0 = np.zeros(len(b4))
jacobi_tol(A4, b4, x0, 1e-3)

Iteración 1: [ 1.5 -2.   1.2  1.5  1.5]
Iteración 2: [ 1.325 -1.6    1.6    1.675  2.425]
Iteración 3: [ 0.89375 -1.35     1.81     1.83125  2.28125]
Iteración 4: [ 0.8146875  -1.08416667  1.935       1.8384375   2.1696875 ]
Iteración 5: [ 0.74486979 -1.01375     1.89258333  1.91638021  2.06622396]
Iteración 6: [ 0.76373568 -0.97863542  1.90132292  1.90592578  2.00092578]
Iteración 7: [ 0.76909668 -0.98549566  1.87160313  1.92160579  1.98816699]
Iteración 8: [ 0.78143139 -0.99196259  1.87141502  1.91380104  1.98024716]
Iteración 9: [ 0.7850751  -0.99873844  1.8646296   1.91522095  1.98538479]
Iteración 10: [ 0.78718101 -1.00174151  1.8658388   1.91274157  1.98672138]
Iteración 11: [ 0.78729533 -1.00286688  1.86536849  1.91281957  1.98914507]


array([ 0.78729533, -1.00286688,  1.86536849,  1.91281957,  1.98914507])

### 4.

In [32]:
def gauss_seidel_tol(A, b, x0, tol):
    n = len(b)
    x = x0.copy()
    iteration = 0
    while True:
        x_new = np.zeros_like(x)
        for i in range(n):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        iteration += 1
        if np.linalg.norm(x_new - x, np.inf) < tol:
            break
        x = x_new
        print(f'Iteración {iteration}: {x}')
    return x

#### a.

In [34]:
x0 = np.zeros(len(b1))
gauss_seidel_tol(A1, b1, x0, 1e-3)

Iteración 1: [ 0.33333333 -0.16666667  0.5       ]
Iteración 2: [ 0.11111111 -0.22222222  0.61904762]
Iteración 3: [ 0.05291005 -0.23280423  0.64852608]
Iteración 4: [ 0.03955656 -0.23595364  0.65559875]
Iteración 5: [ 0.0361492  -0.23660752  0.65733928]


array([ 0.0361492 , -0.23660752,  0.65733928])

#### b.

In [36]:
x0 = np.zeros(len(b2))
gauss_seidel_tol(A2, b2, x0, 1e-3)

Iteración 1: [0.9   0.79  0.758]
Iteración 2: [0.979  0.9495 0.7899]
Iteración 3: [0.99495  0.957475 0.791495]


array([0.99495 , 0.957475, 0.791495])

#### c.

In [38]:
x0 = np.zeros(len(b3))
gauss_seidel_tol(A3, b3, x0, 1e-3)

Iteración 1: [ 0.6    2.2   -0.275]
Iteración 2: [-0.5    2.64  -0.055]
Iteración 3: [-0.72   2.838  0.044]
Iteración 4: [-0.819    2.9271   0.08855]
Iteración 5: [-0.86355    2.967195   0.1085975]
Iteración 6: [-0.8835975   2.98523775  0.11761888]
Iteración 7: [-0.89261888  2.99335699  0.12167849]
Iteración 8: [-0.89667849  2.99701064  0.12350532]
Iteración 9: [-0.89850532  2.99865479  0.12432739]


array([-0.89850532,  2.99865479,  0.12432739])

#### d.

In [40]:
x0 = np.zeros(len(b4))
gauss_seidel_tol(A4, b4, x0, 1e-3)

Iteración 1: [ 1.5     -2.5      1.1      1.525    2.64375]
Iteración 2: [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]
Iteración 3: [ 0.85082845 -1.03530219  1.89436317  1.92747236  2.0093738 ]
Iteración 4: [ 0.7828913  -0.98701859  1.87161643  1.91687229  1.98219533]
Iteración 5: [ 0.78330171 -0.998271    1.86614704  1.91279444  1.98747365]
Iteración 6: [ 0.78616258 -1.00240703  1.86606999  1.91245638  1.98960692]


array([ 0.78616258, -1.00240703,  1.86606999,  1.91245638,  1.98960692])

### 5.

#### a.

In [43]:
A5 = np.array([[2, -1, 1],
               [2, 2, 2],
               [-1, -1, 2]])

b5 = np.array([-1, 4, -5])
x0_5 = np.zeros(len(b5))

# Mostrar que el método de Jacobi falla después de 25 iteraciones
jacobi(A5, b5, x0_5, 25)

Iteración 1: [-0.5  2.  -2.5]
Iteración 2: [ 1.75  5.   -1.75]
Iteración 3: [2.875 2.    0.875]
Iteración 4: [ 0.0625 -1.75   -0.0625]
Iteración 5: [-1.34375  2.      -3.34375]
Iteración 6: [ 2.171875  6.6875   -2.171875]
Iteración 7: [3.9296875 2.        1.9296875]
Iteración 8: [-0.46484375 -3.859375    0.46484375]
Iteración 9: [-2.66210938  2.         -4.66210938]
Iteración 10: [ 2.83105469  9.32421875 -2.83105469]
Iteración 11: [5.57763672 2.         3.57763672]
Iteración 12: [-1.28881836 -7.15527344  1.28881836]
Iteración 13: [-4.7220459  2.        -6.7220459]
Iteración 14: [ 3.86102295 13.4440918  -3.86102295]
Iteración 15: [8.15255737 2.         6.15255737]
Iteración 16: [ -2.57627869 -12.30511475   2.57627869]
Iteración 17: [-7.94069672  2.         -9.94069672]
Iteración 18: [ 5.47034836 19.88139343 -5.47034836]
Iteración 19: [12.1758709  2.        10.1758709]
Iteración 20: [ -4.58793545 -20.35174179   4.58793545]
Iteración 21: [-12.96983862   2.         -14.96983862]
Iteración 

array([-20.82787284,   2.        , -22.82787284])

#### b.

In [46]:
# Gauss-Seidel con tolerancia 10^-5
gauss_seidel_tol(A5, b5, x0_5, 1e-5)

Iteración 1: [-0.5  2.5 -1.5]
Iteración 2: [ 1.5   2.   -0.75]
Iteración 3: [ 0.875  1.875 -1.125]
Iteración 4: [ 1.      2.125  -0.9375]
Iteración 5: [ 1.03125  1.90625 -1.03125]
Iteración 6: [ 0.96875   2.0625   -0.984375]
Iteración 7: [ 1.0234375  1.9609375 -1.0078125]
Iteración 8: [ 0.984375    2.0234375  -0.99609375]
Iteración 9: [ 1.00976562  1.98632812 -1.00195312]
Iteración 10: [ 0.99414062  2.0078125  -0.99902344]
Iteración 11: [ 1.00341797  1.99560547 -1.00048828]
Iteración 12: [ 0.99804688  2.00244141 -0.99975586]
Iteración 13: [ 1.00109863  1.99865723 -1.00012207]
Iteración 14: [ 0.99938965  2.00073242 -0.99993896]
Iteración 15: [ 1.00033569  1.99960327 -1.00003052]
Iteración 16: [ 0.99981689  2.00021362 -0.99998474]
Iteración 17: [ 1.00009918  1.99988556 -1.00000763]
Iteración 18: [ 0.99994659  2.00006104 -0.99999619]
Iteración 19: [ 1.00002861  1.99996758 -1.00000191]
Iteración 20: [ 0.99998474  2.00001717 -0.99999905]
Iteración 21: [ 1.00000811  1.99999094 -1.00000048]
I

array([ 0.99999571,  2.00000477, -0.99999976])

### 6.

#### a.

In [50]:
def is_strictly_diagonally_dominant(A):
    n = A.shape[0]
    for i in range(n):
        sum_row = sum(abs(A[i, j]) for j in range(n) if j != i)
        if abs(A[i, i]) <= sum_row:
            return False
    return True

A6 = np.array([[1, 0, -1],
               [-1/2, 1, -1/4],
               [1, -1/2, 1]])

print("Es estrictamente diagonalmente dominante:", is_strictly_diagonally_dominant(A6))

Es estrictamente diagonalmente dominante: False


#### b.

In [52]:
def gauss_seidel_max_iter(A, b, x0, tol, max_iter):
    n = len(b)
    x = x0.copy()
    iteration = 0
    while iteration < max_iter:
        x_new = np.zeros_like(x)
        for i in range(n):
            s1 = np.dot(A[i, :i], x_new[:i])
            s2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - s1 - s2) / A[i, i]
        iteration += 1
        if np.linalg.norm(x_new - x, np.inf) < tol:
            break
        x = x_new
        print(f'Iteración {iteration}: {x}')
    return x

In [53]:
b6 = np.array([0.2, -1.425, 2])
x0_6 = np.zeros(len(b6))

gauss_seidel_max_iter(A6, b6, x0_6, 1e-22, 300)

Iteración 1: [ 0.2    -1.325   1.1375]
Iteración 2: [ 1.3375    -0.471875   0.4265625]
Iteración 3: [ 0.6265625  -1.00507813  0.87089844]
Iteración 4: [ 1.07089844 -0.67182617  0.59318848]
Iteración 5: [ 0.79318848 -0.88010864  0.7667572 ]
Iteración 6: [ 0.9667572  -0.7499321   0.65827675]
Iteración 7: [ 0.85827675 -0.83129244  0.72607703]
Iteración 8: [ 0.92607703 -0.78044223  0.68370185]
Iteración 9: [ 0.88370185 -0.81222361  0.71018634]
Iteración 10: [ 0.91018634 -0.79236024  0.69363354]
Iteración 11: [ 0.89363354 -0.80477485  0.70397904]
Iteración 12: [ 0.90397904 -0.79701572  0.6975131 ]
Iteración 13: [ 0.8975131  -0.80186517  0.70155431]
Iteración 14: [ 0.90155431 -0.79883427  0.69902855]
Iteración 15: [ 0.89902855 -0.80072858  0.70060715]
Iteración 16: [ 0.90060715 -0.79954464  0.69962053]
Iteración 17: [ 0.89962053 -0.8002846   0.70023717]
Iteración 18: [ 0.90023717 -0.79982212  0.69985177]
Iteración 19: [ 0.89985177 -0.80011117  0.70009264]
Iteración 20: [ 0.90009264 -0.799930

array([ 0.9, -0.8,  0.7])

In [54]:
A6_cambiado = np.array([[1, 0, -2], [-1/2, 1, -1/4], [1, -1/2, 1]])
b6_cambiado = np.array([0.2, -1.425, 2])

x0_6_cambiado = np.zeros(len(b6_cambiado))

gauss_seidel_max_iter(A6_cambiado, b6_cambiado, x0_6_cambiado, 1e-22, 300)

Iteración 1: [ 0.2    -1.325   1.1375]
Iteración 2: [ 2.475      0.096875  -0.4265625]
Iteración 3: [-0.653125   -1.85820313  1.72402344]
Iteración 4: [ 3.64804688  0.8300293  -1.23303223]
Iteración 5: [-2.26606445 -2.86629028  2.83291931]
Iteración 6: [ 5.86583862  2.21614914 -2.75776405]
Iteración 7: [-5.31552811 -4.77220507  4.92942557]
Iteración 8: [10.05885115  4.83678197 -5.64046016]
Iteración 9: [-11.08092033  -8.3755752    8.89313272]
Iteración 10: [ 17.98626545   9.79141591 -11.0905575 ]
Iteración 11: [-21.98111499 -15.18819687  16.38701656]
Iteración 12: [ 32.97403311  19.1587707  -21.39464777]
Iteración 13: [-42.58929553 -28.06830971  30.55514068]
Iteración 14: [ 61.31028136  36.86892585 -40.87581843]
Iteración 15: [-81.55163687 -52.41977304  57.34175035]
Iteración 16: [114.88350069  70.35218793 -77.70740673]
Iteración 17: [-155.21481345  -98.45925841  107.98518425]
Iteración 18: [ 216.1703685   133.65648031 -147.34212834]
Iteración 19: [-294.48425668 -185.50266043  203.7329

array([ 2.15687283e+41,  1.34804552e+41, -1.48285007e+41])

El algoritmo se dispara de manera descontrolada con un pequeño cambio en el sistema de ecuaciones

### 8.

#### a.

In [85]:
A8 = np.array([
    [-4, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0],
    [-1, -4, -1,  0,  0, -1,  0,  0,  0,  0,  0,  0],
    [ 0, -1, -4, -1,  0,  0, -1,  0,  0,  0,  0,  0],
    [ 0,  0, -1, -4,  0,  0,  0, -1,  0,  0,  0, -1],
    [-1,  0,  0,  0, -4, -1,  0,  0, -1,  0,  0,  0],
    [ 0, -1,  0,  0, -1, -4, -1,  0,  0, -1,  0,  0],
    [ 0,  0, -1,  0,  0, -1, -4, -1,  0,  0, -1,  0],
    [ 0,  0,  0, -1,  0,  0, -1, -4,  0,  0,  0, -1],
    [ 0,  0,  0,  0, -1,  0,  0,  0, -4, -1,  0,  0],
    [ 0,  0,  0,  0,  0, -1,  0,  0, -1, -4, -1,  0],
    [ 0,  0,  0,  0,  0,  0, -1,  0,  0, -1, -4, -1],
    [ 0,  0,  0, -1,  0,  0,  0, -1,  0,  0, -1, -4]
])

b8 = np.array([220, 110, 110, 220, 220, 110, 110, 220, 220, 110, 110, 220])


def is_strictly_diagonally_dominant(A):
    n = A.shape[0]
    for i in range(n):
        sum_row = sum(abs(A[i, j]) for j in range(n) if j != i)
        if abs(A[i, i]) <= sum_row:
            return False
    return True

print("Es estrictamente diagonalmente dominante:", is_strictly_diagonally_dominant(A8))

Es estrictamente diagonalmente dominante: False


#### b.

In [89]:
x_0_8 = np.zeros(len(b8))

# Tolerance
tol = 1e-2

def jacobi_method(A, b, x0, tol, max_iterations=1000):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = np.zeros_like(x)
        for i in range(n):
            sum_Ax = sum(A[i][j] * x[j] for j in range(n) if i != j)
            x_new[i] = (b[i] - sum_Ax) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new
        x = x_new
    raise ValueError("Jacobi method did not converge within the maximum number of iterations")

In [91]:
x_jacobi = jacobi_method(A8, b8, x_0_8, tol)
x_jacobi

array([-45.62734772,  -8.82852785, -15.00729335, -33.74707967,
       -28.67263752, -14.06978606,  -7.41673933, -36.2778221 ,
       -45.62734772,  -8.82852785, -15.00729335, -33.74707967])

In [93]:
def gauss_seidel_method(A, b, x0, tol, max_iterations=1000):
    n = len(b)
    x = x0.copy()
    for k in range(max_iterations):
        x_new = x.copy()
        for i in range(n):
            sum1 = sum(A[i][j] * x_new[j] for j in range(i))
            sum2 = sum(A[i][j] * x[j] for j in range(i + 1, n))
            x_new[i] = (b[i] - sum1 - sum2) / A[i][i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new
        x = x_new
    raise ValueError("Gauss-Seidel method did not converge within the maximum number of iterations")

In [97]:
x_gauss_seidel = gauss_seidel_method(A8, b8, x_0_8, tol)
x_gauss_seidel

array([-45.61850783,  -8.83436866, -14.9984752 , -33.74637399,
       -28.67814468, -14.05743481,  -7.41871731, -36.27231059,
       -45.62193115,  -8.83044394, -15.0012931 , -33.74500558])